name: industrial_ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**/build_docker_image.yaml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**/build_docker_image.yaml'

env:
  UPSTREAM_WORKSPACE: .ci.rosinstall

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: foxy, ROS_REPO: ros}
          - { ROS_DISTRO: galactic, ROS_REPO: ros}
          - { ROS_DISTRO: humble, ROS_REPO: ros}
          - { ROS_DISTRO: rolling, ROS_REPO: ros}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}
